site_name: Acquia Cog Tools Documentation

repo_url: https://github.com/acquia-pso/cog_tools
site_description: 'Cog Tools - A Drupal 8 sub theme generator, with build tools. '
theme: readthedocs
strict: true

markdown_extensions:
  - toc:
      permalink: True

pages:
  - Home: 'index.md'
  - Getting started:
    - Setup: 'setup-full.md'
  - Project documentation:
    - Cog theme:
          - About Cog: 'about-cog.md'
    - Theme guide:
        - Overview: 'about-theming-guide.md'
        - Advagg: 'advagg.md'
        - Fonts: 'fonts.md'
        - Images: 'images.md'
        - JavaScript: 'javascript.md'
        - Libraries: 'libraries.md'
        - Preprocessing: 'preprocessing.md'
        - Sass Style Organization: 'sass.md'
        - Component Rules with Media Queries: 'sass.md'
        - CSS Preprocessing: 'sass.md'
        - Twig: 'twig.md'
  - Support & Contribution: 'CONTRIBUTING.md'
